@startuml C4_Elements
    !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
    !define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
    !define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
    ' uncomment the following line and comment the first to use locally
    ' !include C4_Container.puml
    !include DEVICONS/angular.puml
    !include DEVICONS/dotnet.puml
    !include DEVICONS/java.puml
    !include DEVICONS/sqllite.puml
    !include FONTAWESOME/server.puml
    !include FONTAWESOME/envelope.puml

    ' LAYOUT_TOP_DOWN()
    ' LAYOUT_AS_SKETCH()
    LAYOUT_WITH_LEGEND()
    SHOW_PERSON_OUTLINE()
    Person(comerciante, "Comerciante", "Gestor do comércio")
    AddBoundaryTag("v1", $bgColor="lightgreen", $fontColor="green", $borderColor="green")
    AddBoundaryTag("v2", $bgColor="lightgray", $fontColor="red", $borderColor="red")
    System_Boundary(solution, "FluxoCaixa") {  
        Boundary(to_implement, "Não implementado", $type="Frontend Web/Mobile", $tags="v2") {  
            Container(spas, "Single-Page App", "angular ou react ou ...", "(Implementação futura) Interface principal Web que irá consumir as APIs")
            Container(mobile_app, "Mobile", "Xamarim", "(Implementação futura) Interface principal Mobile que irá consumir as APIs")
        }
        Boundary(to_implement2, "Não implementado", $type="SSO/Security", $tags="v2") {  
            Container(sso, "SSO", "Federations", "(Implementação futura) Unico ponto de autenticação e/ou Federações confiaveis como Google/Facebook e outros, podendo também ser Azure AD/Amazon Cognito")
        }
        Boundary(web_api, "Concluído", $type="Backend Web API", $tags="v1") {  
            System(microservico_fluxo_caixa, "Microserviço Fluxo de caixa (Dotnet Core 7)", "(MVP Implementado) Microservico que permite a gestão do fluxo de caixa, e a visão do seu consolidado", "dotnet")
            ContainerDb(database, "Database", "SQLLite Database", "Registra os lançamentos do fluxo de caixa em um banco relacional","sqllite")
        }
    }   

    Rel(comerciante, spas, "controla através do", "FLUXO DE CAIXA")
    Rel(comerciante, mobile_app, "controla através do", "FLUXO DE CAIXA")
    Rel(spas, microservico_fluxo_caixa, "Requisita", "API")
    Rel(spas, sso, "requisita autenticacao se não autenticado ou expirado", "FLUXO DE CAIXA")
    Rel(mobile_app, sso, "requisita autenticacao se não autenticado ou expirado", "FLUXO DE CAIXA")
    Rel(mobile_app, microservico_fluxo_caixa, "Requisita", "API")
    Rel(microservico_fluxo_caixa, database, "controla através do", "FLUXO DE CAIXA")
    SHOW_LEGEND()
@enduml